language: java
dist: trusty
jdk:
- openjdk11
jobs:
  include:
  - stage: test
    script: mvn test -Dhdf5lib-absolute-path=`pwd`/lib/linux64/libjhdf5.so --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true 
  - stage: GitHub Release
    script: skip
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      on:
        tags: true
        all_branches: true

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - export MAVEN_OPTS="-Xmx2500m"
