name: Cloudsmith Deployment

on:
  schedule:
    - cron: '0 1 * * 1' 



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn test -Dhdf5lib-absolute-path=`pwd`/lib/linux64/libjhdf5.so -DforkMode=always --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true
      
      - name: Set up Cloudsmith
        uses: actions/setup-java@v2
        with: # running setup-java again overwrites the settings.xml
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
          server-id: msm # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: CLOUDSMITH_USERNAME # env variable for username in deploy
          server-password: CLOUDSMITH_TOKEN # env variable for token in deploy       

      - name: Publish to Cloudsmith
        run: mvn deploy -DskipTests=true --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true
        env:
          CLOUDSMITH_USERNAME: nico-kuhnel
          CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_API_KEY }}
